/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package relytest.ui;

import java.awt.Window;
import java.util.Enumeration;
import java.util.HashMap;
import java.util.Map;
import javax.swing.AbstractButton;
import javax.swing.SwingUtilities;

/**
 *
 * @author Gabriela Sanchez - Miguel Sanchez
 */
public class LookAndFeelForm extends javax.swing.JFrame {

    /**
     * Creates new form LookAndFeelForm
     */
    private Map<String, Integer> mapLaF;
    private PropertiesMgr p;

    public LookAndFeelForm() {
        initComponents();

        mapLaF = new HashMap<>();
        p = new PropertiesMgr();
        
        buttonGroupLaF.add(jRadioButtonAcryl);
        buttonGroupLaF.add(jRadioButtonAero);
        buttonGroupLaF.add(jRadioButtonAluminium);
        buttonGroupLaF.add(jRadioButtonBernstein);
        buttonGroupLaF.add(jRadioButtonFast);
        buttonGroupLaF.add(jRadioButtonGraphite);
        buttonGroupLaF.add(jRadioButtonHiFi);
        buttonGroupLaF.add(jRadioButtonLuna);
        buttonGroupLaF.add(jRadioButtonMcWin);
        buttonGroupLaF.add(jRadioButtonMint);
        buttonGroupLaF.add(jRadioButtonNoire);
        buttonGroupLaF.add(jRadioButtonSmart);
        buttonGroupLaF.add(jRadioButtonTexture);

        mapLaF.put(Constants.LAF_NAMES[Constants.LAF_ACRYL], Constants.LAF_ACRYL);
        mapLaF.put(Constants.LAF_NAMES[Constants.LAF_AERO], Constants.LAF_AERO);
        mapLaF.put(Constants.LAF_NAMES[Constants.LAF_ALUMINIUM], Constants.LAF_ALUMINIUM);
        mapLaF.put(Constants.LAF_NAMES[Constants.LAF_BERNSTEIN], Constants.LAF_BERNSTEIN);
        mapLaF.put(Constants.LAF_NAMES[Constants.LAF_FAST], Constants.LAF_FAST);
        mapLaF.put(Constants.LAF_NAMES[Constants.LAF_GRAPHITE], Constants.LAF_GRAPHITE);
        mapLaF.put(Constants.LAF_NAMES[Constants.LAF_HIFI], Constants.LAF_HIFI);
        mapLaF.put(Constants.LAF_NAMES[Constants.LAF_LUNA], Constants.LAF_LUNA);
        mapLaF.put(Constants.LAF_NAMES[Constants.LAF_MCWIN], Constants.LAF_MCWIN);
        mapLaF.put(Constants.LAF_NAMES[Constants.LAF_MINT], Constants.LAF_MINT);
        mapLaF.put(Constants.LAF_NAMES[Constants.LAF_NOIRE], Constants.LAF_NOIRE);
        mapLaF.put(Constants.LAF_NAMES[Constants.LAF_SMART], Constants.LAF_SMART);
        mapLaF.put(Constants.LAF_NAMES[Constants.LAF_TEXTURE], Constants.LAF_TEXTURE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupLaF = new javax.swing.ButtonGroup();
        jButtonUpdate = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jRadioButtonAcryl = new javax.swing.JRadioButton();
        jRadioButtonAero = new javax.swing.JRadioButton();
        jRadioButtonAluminium = new javax.swing.JRadioButton();
        jRadioButtonBernstein = new javax.swing.JRadioButton();
        jRadioButtonFast = new javax.swing.JRadioButton();
        jRadioButtonMcWin = new javax.swing.JRadioButton();
        jRadioButtonLuna = new javax.swing.JRadioButton();
        jRadioButtonSmart = new javax.swing.JRadioButton();
        jRadioButtonGraphite = new javax.swing.JRadioButton();
        jRadioButtonNoire = new javax.swing.JRadioButton();
        jRadioButtonHiFi = new javax.swing.JRadioButton();
        jRadioButtonMint = new javax.swing.JRadioButton();
        jRadioButtonTexture = new javax.swing.JRadioButton();

        setTitle("Look and Feel");

        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jRadioButtonAcryl.setText("Acryl");
        jRadioButtonAcryl.setName(""); // NOI18N

        jRadioButtonAero.setText("Aero");

        jRadioButtonAluminium.setSelected(true);
        jRadioButtonAluminium.setText("Aluminium");

        jRadioButtonBernstein.setText("Bernstein");

        jRadioButtonFast.setText("Fast");

        jRadioButtonMcWin.setText("McWin");

        jRadioButtonLuna.setText("Luna");

        jRadioButtonSmart.setText("Smart");

        jRadioButtonGraphite.setText("Graphite");

        jRadioButtonNoire.setText("Noire");

        jRadioButtonHiFi.setText("HiFi");

        jRadioButtonMint.setText("Mint");

        jRadioButtonTexture.setText("Texture");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonAluminium)
                    .addComponent(jRadioButtonBernstein)
                    .addComponent(jRadioButtonAero)
                    .addComponent(jRadioButtonFast)
                    .addComponent(jRadioButtonAcryl))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonMcWin)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonGraphite)
                            .addComponent(jRadioButtonHiFi)
                            .addComponent(jRadioButtonLuna)
                            .addComponent(jRadioButtonMint))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonTexture)
                            .addComponent(jRadioButtonSmart)
                            .addComponent(jRadioButtonNoire))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonAcryl)
                    .addComponent(jRadioButtonGraphite)
                    .addComponent(jRadioButtonNoire))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonAero)
                    .addComponent(jRadioButtonHiFi)
                    .addComponent(jRadioButtonSmart))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonAluminium)
                    .addComponent(jRadioButtonLuna)
                    .addComponent(jRadioButtonTexture))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonBernstein)
                    .addComponent(jRadioButtonMcWin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonFast)
                    .addComponent(jRadioButtonMint))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonUpdate)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUpdate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:
        AbstractButton selectedButton = null;
        for (Enumeration<AbstractButton> buttons = buttonGroupLaF.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                selectedButton = button;
                break;
            }
        }

        if (selectedButton != null) {
            LookAndFeelMgr laf = new LookAndFeelMgr();
            laf.setLookAndFeel(mapLaF.get(selectedButton.getText()));

            Window windows[] = Window.getWindows();
            for (Window window : windows) {
                if (window.isDisplayable()) {
                    SwingUtilities.updateComponentTreeUI(window);
                }
            }

            p.setValue(Constants.KEY_LOOK_AND_FEEL, mapLaF.get(selectedButton.getText()).toString());
        }
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LookAndFeelForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new LookAndFeelForm().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupLaF;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonAcryl;
    private javax.swing.JRadioButton jRadioButtonAero;
    private javax.swing.JRadioButton jRadioButtonAluminium;
    private javax.swing.JRadioButton jRadioButtonBernstein;
    private javax.swing.JRadioButton jRadioButtonFast;
    private javax.swing.JRadioButton jRadioButtonGraphite;
    private javax.swing.JRadioButton jRadioButtonHiFi;
    private javax.swing.JRadioButton jRadioButtonLuna;
    private javax.swing.JRadioButton jRadioButtonMcWin;
    private javax.swing.JRadioButton jRadioButtonMint;
    private javax.swing.JRadioButton jRadioButtonNoire;
    private javax.swing.JRadioButton jRadioButtonSmart;
    private javax.swing.JRadioButton jRadioButtonTexture;
    // End of variables declaration//GEN-END:variables
}
