/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package relytest.ui;

import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author Gabriela Sanchez - Miguel Sanchez
 */
public class MainForm extends javax.swing.JFrame {

    private ConfigForm configFrm;

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        loadTimes();
    }

    private void loadTimes() {
        PropertiesMgr p = new PropertiesMgr();
        String value = p.getValue(Constants.Key_ShortTime);
        Integer i = Integer.parseInt(value);
        jToggleButtonShort.setText("Short " + i + " Mins");
        i = Integer.parseInt(p.getValue(Constants.Key_LongTime));
        jToggleButtonMedium.setText("Long " + i + " Mins");
    }

    private String getTotalTime() {
        PropertiesMgr p = new PropertiesMgr();
        String value;
        Integer i;
        if (jToggleButtonShort.isSelected()) {

            value = p.getValue(Constants.Key_ShortTime);
            i = Integer.parseInt(value);
            return "0:" + i + ":00";
        } else if (jToggleButtonMedium.isSelected()) {
            value = p.getValue(Constants.Key_LongTime);
            i = Integer.parseInt(value);
            return "0:" + i + ":00";
        } else {
            return "0:60:00";
        }
    }

    private void start() {
        if (jTextFieldCharterName.getText().equals("")) {
            showMessageDialog(this, "Please insert the name of the charter.");
        } else {
            MisionForm mision = new MisionForm();
            mision.setTotalTime(getTotalTime());
            mision.setMisionName("RelyTest - Charter: " + jTextFieldCharterName.getText());
            mision.setTitle("RelyTest - Charter: " + jTextFieldCharterName.getText());
            mision.Start();
            mision.show();
            mision.setLocationRelativeTo(null);
            this.setVisible(false);
        }
    }

    private void config() {
        configFrm = new ConfigForm(this);
        configFrm.setLocationRelativeTo(null);
        configFrm.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        durationButtonGroup = new javax.swing.ButtonGroup();
        jButtonStart = new javax.swing.JButton();
        jButtonConfig = new javax.swing.JButton();
        jPanelDuration = new javax.swing.JPanel();
        jToggleButtonShort = new javax.swing.JToggleButton();
        jToggleButtonMedium = new javax.swing.JToggleButton();
        jToggleButtonRelyTest = new javax.swing.JToggleButton();
        jPanelCharter = new javax.swing.JPanel();
        jTextFieldCharterName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RelyTest");

        jButtonStart.setText("Start");
        jButtonStart.setFocusPainted(false);
        jButtonStart.setMaximumSize(new java.awt.Dimension(113, 23));
        jButtonStart.setMinimumSize(new java.awt.Dimension(113, 23));
        jButtonStart.setPreferredSize(new java.awt.Dimension(113, 23));
        jButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartActionPerformed(evt);
            }
        });

        jButtonConfig.setText("Config");
        jButtonConfig.setFocusPainted(false);
        jButtonConfig.setMaximumSize(new java.awt.Dimension(113, 23));
        jButtonConfig.setMinimumSize(new java.awt.Dimension(113, 23));
        jButtonConfig.setPreferredSize(new java.awt.Dimension(113, 23));
        jButtonConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfigActionPerformed(evt);
            }
        });

        jPanelDuration.setBorder(javax.swing.BorderFactory.createTitledBorder("Duration:"));

        durationButtonGroup.add(jToggleButtonShort);
        jToggleButtonShort.setSelected(true);
        jToggleButtonShort.setText("Short (15min)");
        jToggleButtonShort.setFocusPainted(false);
        jToggleButtonShort.setMaximumSize(new java.awt.Dimension(113, 23));
        jToggleButtonShort.setMinimumSize(new java.awt.Dimension(113, 23));
        jToggleButtonShort.setPreferredSize(new java.awt.Dimension(113, 23));
        jToggleButtonShort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonShortActionPerformed(evt);
            }
        });

        durationButtonGroup.add(jToggleButtonMedium);
        jToggleButtonMedium.setText("Long (30min)");
        jToggleButtonMedium.setFocusPainted(false);
        jToggleButtonMedium.setMaximumSize(new java.awt.Dimension(113, 23));
        jToggleButtonMedium.setMinimumSize(new java.awt.Dimension(113, 23));
        jToggleButtonMedium.setPreferredSize(new java.awt.Dimension(113, 23));

        durationButtonGroup.add(jToggleButtonRelyTest);
        jToggleButtonRelyTest.setText("RelyTest (60min)");
        jToggleButtonRelyTest.setFocusPainted(false);
        jToggleButtonRelyTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonRelyTestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDurationLayout = new javax.swing.GroupLayout(jPanelDuration);
        jPanelDuration.setLayout(jPanelDurationLayout);
        jPanelDurationLayout.setHorizontalGroup(
            jPanelDurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDurationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToggleButtonShort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButtonMedium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButtonRelyTest)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanelDurationLayout.setVerticalGroup(
            jPanelDurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToggleButtonShort, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
            .addComponent(jToggleButtonMedium, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToggleButtonRelyTest, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelCharter.setBorder(javax.swing.BorderFactory.createTitledBorder("Charter:"));
        jPanelCharter.setName("Charter"); // NOI18N

        javax.swing.GroupLayout jPanelCharterLayout = new javax.swing.GroupLayout(jPanelCharter);
        jPanelCharter.setLayout(jPanelCharterLayout);
        jPanelCharterLayout.setHorizontalGroup(
            jPanelCharterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCharterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldCharterName, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCharterLayout.setVerticalGroup(
            jPanelCharterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCharterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldCharterName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelDuration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addComponent(jPanelCharter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCharter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConfig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanelCharter.getAccessibleContext().setAccessibleName("Charter:");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonShortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonShortActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jToggleButtonShortActionPerformed

    private void jToggleButtonRelyTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonRelyTestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonRelyTestActionPerformed

    private void jButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartActionPerformed
        start();
    }//GEN-LAST:event_jButtonStartActionPerformed

    private void jButtonConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfigActionPerformed
        config();
    }//GEN-LAST:event_jButtonConfigActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup durationButtonGroup;
    private javax.swing.JButton jButtonConfig;
    private javax.swing.JButton jButtonStart;
    private javax.swing.JPanel jPanelCharter;
    private javax.swing.JPanel jPanelDuration;
    private javax.swing.JTextField jTextFieldCharterName;
    private javax.swing.JToggleButton jToggleButtonMedium;
    private javax.swing.JToggleButton jToggleButtonRelyTest;
    private javax.swing.JToggleButton jToggleButtonShort;
    // End of variables declaration//GEN-END:variables
}
