/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package relytest.ui.forms;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import relytest.ui.common.CharterDto;
import static javax.swing.JOptionPane.showMessageDialog;
import relytest.interfaces.IConfigFormLoad;
import relytest.internationalization.LanguageController;
import relytest.internationalization.Texts;
import relytest.ui.Constants;
import relytest.ui.PropertiesMgr;

/**
 *
 * @author Gabriela Sanchez - Miguel Sanchez
 */
public final class MainForm extends javax.swing.JFrame implements IConfigFormLoad{

    private ConfigForm configFrm;
    private final LanguageController lCon;

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        this.lCon = new LanguageController();
        initComponents();
        loadTimes();
        
        jTextFieldPath.setText(System.getProperty("user.dir"));
        loadLanguage();
    }

    private void loadLanguage() {        
        setTitle(lCon.getValue(Texts.MainForm_Title));
        jPanelCharter.setBorder(javax.swing.BorderFactory.createTitledBorder(lCon.getValue(Texts.MainForm_jPanelCharter)));
        jPanelDuration.setBorder(javax.swing.BorderFactory.createTitledBorder(lCon.getValue(Texts.MainForm_jPanelDuration)));
        jButtonPath.setText(lCon.getValue(Texts.MainForm_jButtonPath));        
    }
    
    @Override
    public void loadTimes() {
        PropertiesMgr p = new PropertiesMgr();       
        String value = p.getValue(Constants.KEY_SHORT_TIME);
        Integer i = Integer.parseInt(value);
        jToggleButtonShort.setText(lCon.getValue(Texts.MainForm_jToggleButtonShort)+" " + i + " Mins");
        i = Integer.parseInt(p.getValue(Constants.KEY_LONG_TIME));
        jToggleButtonLong.setText(lCon.getValue(Texts.MainForm_jToggleButtonLong)+" " + i + " Mins");
        i = Integer.parseInt(p.getValue(Constants.KEY_MEDIUM_TIME));
        jToggleButtonMedium.setText(lCon.getValue(Texts.MainForm_jToggleButtonMedium)+" " + i + " Mins");
    }

    private String getTotalTime() {
        PropertiesMgr p = new PropertiesMgr();
        String value;
        Integer i;
        if (jToggleButtonShort.isSelected()) {
            value = p.getValue(Constants.KEY_SHORT_TIME);
        } else if (jToggleButtonMedium.isSelected()) {
            value = p.getValue(Constants.KEY_MEDIUM_TIME);
        } else {
            value = p.getValue(Constants.KEY_LONG_TIME);
        }
        i = Integer.parseInt(value);
        return timeToHhMmSs(i);
    }

    private String timeToHhMmSs(Integer time) {
        if (time < 60) {
            return "0:" + time + ":00";
        } else {
            Integer hour = time / 60;
            Integer mins = time % 60;
            return hour + ":" + mins + ":00";
        }
    }
            
    private void start() {
        if (jTextFieldCharterName.getText().equals("")) {
            showMessageDialog(this, lCon.getValue(Texts.Msg_InsertNameCharter));
        } else {
            String charterName = jTextFieldCharterName.getText().replaceAll("[^a-zA-Z0-9.-]", "_");
            CharterDto dto = new CharterDto(jTextFieldCharterName.getText());
            dto.setCharterFileName(charterName);
            dto.setTotalTime(getTotalTime());
            dto.getDetails().getPlanification().setDuration(getTotalTime());
            
            MisionForm mision = new MisionForm(dto);
               
            mision.setTitle(lCon.getValue(Texts.MisionForm_Title)+ " "+ charterName);
            mision.setMainForm(this);
            mision.Start();
            mision.show();
            mision.pack();
            mision.setLocationRelativeTo(this);
            jTextFieldCharterName.setText("");
            this.setVisible(false);
        }
    }

    public boolean isAlphaNumeric(String s) {
        String pattern = "^[a-zA-Z0-9]*$";
        return s.matches(pattern);
    }

    private void config() {
        configFrm = new ConfigForm(this);
        configFrm.pack();
        configFrm.setLocationRelativeTo(this);
        configFrm.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        durationButtonGroup = new javax.swing.ButtonGroup();
        jButtonStart = new javax.swing.JButton();
        jButtonConfig = new javax.swing.JButton();
        jPanelDuration = new javax.swing.JPanel();
        jToggleButtonShort = new javax.swing.JToggleButton();
        jToggleButtonMedium = new javax.swing.JToggleButton();
        jToggleButtonLong = new javax.swing.JToggleButton();
        jPanelCharter = new javax.swing.JPanel();
        jTextFieldCharterName = new javax.swing.JTextField();
        jToolBar = new javax.swing.JToolBar();
        jButtonPath = new javax.swing.JButton();
        jTextFieldPath = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RelyTest");

        jButtonStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/start.png"))); // NOI18N
        jButtonStart.setToolTipText("Starts a New Charter");
        jButtonStart.setFocusPainted(false);
        jButtonStart.setMaximumSize(new java.awt.Dimension(113, 23));
        jButtonStart.setMinimumSize(new java.awt.Dimension(113, 23));
        jButtonStart.setPreferredSize(new java.awt.Dimension(113, 23));
        jButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartActionPerformed(evt);
            }
        });

        jButtonConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/tool.png"))); // NOI18N
        jButtonConfig.setToolTipText("Opens the Configuration Window");
        jButtonConfig.setFocusPainted(false);
        jButtonConfig.setMaximumSize(new java.awt.Dimension(113, 23));
        jButtonConfig.setMinimumSize(new java.awt.Dimension(113, 23));
        jButtonConfig.setPreferredSize(new java.awt.Dimension(113, 23));
        jButtonConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfigActionPerformed(evt);
            }
        });

        jPanelDuration.setBorder(javax.swing.BorderFactory.createTitledBorder("Duration:"));

        durationButtonGroup.add(jToggleButtonShort);
        jToggleButtonShort.setSelected(true);
        jToggleButtonShort.setText("Short (15min)");
        jToggleButtonShort.setFocusPainted(false);
        jToggleButtonShort.setMaximumSize(new java.awt.Dimension(113, 23));
        jToggleButtonShort.setMinimumSize(new java.awt.Dimension(113, 23));
        jToggleButtonShort.setPreferredSize(new java.awt.Dimension(113, 23));
        jToggleButtonShort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonShortActionPerformed(evt);
            }
        });

        durationButtonGroup.add(jToggleButtonMedium);
        jToggleButtonMedium.setText("Medium (30min)");
        jToggleButtonMedium.setFocusPainted(false);
        jToggleButtonMedium.setMaximumSize(new java.awt.Dimension(113, 23));
        jToggleButtonMedium.setMinimumSize(new java.awt.Dimension(113, 23));
        jToggleButtonMedium.setPreferredSize(new java.awt.Dimension(113, 23));

        durationButtonGroup.add(jToggleButtonLong);
        jToggleButtonLong.setText("Long (60min)");
        jToggleButtonLong.setFocusPainted(false);
        jToggleButtonLong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonLongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDurationLayout = new javax.swing.GroupLayout(jPanelDuration);
        jPanelDuration.setLayout(jPanelDurationLayout);
        jPanelDurationLayout.setHorizontalGroup(
            jPanelDurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDurationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToggleButtonShort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButtonMedium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButtonLong)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDurationLayout.setVerticalGroup(
            jPanelDurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToggleButtonShort, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
            .addComponent(jToggleButtonMedium, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToggleButtonLong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelCharter.setBorder(javax.swing.BorderFactory.createTitledBorder("Charter:"));
        jPanelCharter.setName("Charter"); // NOI18N

        jTextFieldCharterName.setToolTipText("What are you going to test?");
        jTextFieldCharterName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCharterNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCharterLayout = new javax.swing.GroupLayout(jPanelCharter);
        jPanelCharter.setLayout(jPanelCharterLayout);
        jPanelCharterLayout.setHorizontalGroup(
            jPanelCharterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCharterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldCharterName, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelCharterLayout.setVerticalGroup(
            jPanelCharterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCharterLayout.createSequentialGroup()
                .addComponent(jTextFieldCharterName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jToolBar.setFloatable(false);
        jToolBar.setRollover(true);

        jButtonPath.setText("Workspace:");
        jButtonPath.setFocusable(false);
        jButtonPath.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonPath.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPathActionPerformed(evt);
            }
        });
        jToolBar.add(jButtonPath);

        jTextFieldPath.setEditable(false);
        jTextFieldPath.setText("Path");
        jToolBar.add(jTextFieldPath);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addComponent(jToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanelDuration, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelCharter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCharter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonStart, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(jButtonConfig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonShortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonShortActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jToggleButtonShortActionPerformed

    private void jToggleButtonLongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonLongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonLongActionPerformed

    private void jButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartActionPerformed
        start();
    }//GEN-LAST:event_jButtonStartActionPerformed

    private void jButtonConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfigActionPerformed
        config();
    }//GEN-LAST:event_jButtonConfigActionPerformed

    private void jButtonPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPathActionPerformed

        try {
            File file = new File (System.getProperty("user.dir"));
            Desktop desktop = Desktop.getDesktop();
            desktop.open(file);
            // TODO add your handling code here:
        } catch (IOException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonPathActionPerformed

    private void jTextFieldCharterNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCharterNameActionPerformed
        // TODO add your handling code here:
        start();
    }//GEN-LAST:event_jTextFieldCharterNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup durationButtonGroup;
    private javax.swing.JButton jButtonConfig;
    private javax.swing.JButton jButtonPath;
    private javax.swing.JButton jButtonStart;
    private javax.swing.JPanel jPanelCharter;
    private javax.swing.JPanel jPanelDuration;
    private javax.swing.JTextField jTextFieldCharterName;
    private javax.swing.JTextField jTextFieldPath;
    private javax.swing.JToggleButton jToggleButtonLong;
    private javax.swing.JToggleButton jToggleButtonMedium;
    private javax.swing.JToggleButton jToggleButtonShort;
    private javax.swing.JToolBar jToolBar;
    // End of variables declaration//GEN-END:variables
}
